# Site settings
title: Patrick Emami
description: > # this means to ignore newlines until "baseurl:"
  My summaries of Machine Learning papers, investigations into various mathematical and CS topics, and the occasional tutorial.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pemami4911.github.io" # the base hostname & protocol for your site
twitter_username: patrickomid
github_username:  pemami4911

# Build settings
markdown: kramdown
