# Site settings
title: KZhou's blog
description: > # this means to ignore newlines until "baseurl:"
  My summaries of Machine Learning/Computer Vision and Application. Mainly concerning artificial intelligence

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://KissyZhou.github.io" # the base hostname & protocol for your site
github_username:  KissyZhou

# Build settings
markdown: kramdown

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: KissyZhou.github.io    #仓库名称
  owner: KissyZhou    #github用户名
  admin: KissyZhou
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-132553416-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Redirection
plugins:
  - jekyll-redirect-from
